export default {
  interface: {
    ApprovalForAll: {
      name: "ApprovalForAll",
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "account",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "operator",
          type: "address",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "approved",
          type: "bool",
        },
      ],
      type: "event",
      signature:
        "0x17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31",
    },
    Purchase_record: {
      name: "Purchase_record",
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "_from",
          type: "address",
        },
        {
          indexed: false,
          internalType: "address",
          name: "_to",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "price",
          type: "uint256",
        },
      ],
      type: "event",
      signature:
        "0x15fbd3d61816efdccde1f3a60e4221f1653e93db3b81f2d38dd7facd1118a3dd",
    },
    Purchase_record_batch: {
      name: "Purchase_record_batch",
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "_from",
          type: "address",
        },
        {
          indexed: false,
          internalType: "address",
          name: "_to",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256[]",
          name: "tokenIds",
          type: "uint256[]",
        },
        {
          indexed: false,
          internalType: "uint256[]",
          name: "amounts",
          type: "uint256[]",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "price",
          type: "uint256",
        },
      ],
      type: "event",
      signature:
        "0x00938902841bac23d916473d4c49d803ba85671c74755855cb9ed782a06c564d",
    },
    TransferBatch: {
      name: "TransferBatch",
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "operator",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "from",
          type: "address",
        },
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: false,
          internalType: "uint256[]",
          name: "ids",
          type: "uint256[]",
        },
        {
          indexed: false,
          internalType: "uint256[]",
          name: "values",
          type: "uint256[]",
        },
      ],
      type: "event",
      signature:
        "0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb",
    },
    TransferSingle: {
      name: "TransferSingle",
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "operator",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "from",
          type: "address",
        },
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: false,
          internalType: "uint256",
          name: "id",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "value",
          type: "uint256",
        },
      ],
      type: "event",
      signature:
        "0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62",
    },
    URI: {
      name: "URI",
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "string",
          name: "value",
          type: "string",
        },
        { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      ],
      type: "event",
      signature:
        "0x6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b",
    },
    mint_record: {
      name: "mint_record",
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "tokenCreator",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
        { indexed: false, internalType: "bool", name: "nft", type: "bool" },
      ],
      type: "event",
      signature:
        "0x528cc4ddfd2fa8cab10c682735ae9d9416c7c7810f001f2582ab03eb09d4a363",
    },
    royalty_record: {
      name: "royalty_record",
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "tokenOwner",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "royaltySetup",
          type: "uint256",
        },
      ],
      type: "event",
      signature:
        "0x4ad85eb1f0c50f4b5575b4169e72166bba50a24202a5ce2d33c67537e2ebf309",
    },
    balanceOf: {
      name: "balanceOf",
      inputs: [
        { internalType: "address", name: "account", type: "address" },
        { internalType: "uint256", name: "id", type: "uint256" },
      ],
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
      signature: "0x00fdd58e",
    },
    balanceOfBatch: {
      name: "balanceOfBatch",
      inputs: [
        { internalType: "address[]", name: "accounts", type: "address[]" },
        { internalType: "uint256[]", name: "ids", type: "uint256[]" },
      ],
      outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
      stateMutability: "view",
      type: "function",
      signature: "0x4e1273f4",
    },
    currentOwners: {
      name: "currentOwners",
      inputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "address", name: "", type: "address" },
      ],
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
      signature: "0xd24c0b0b",
    },
    isApprovedForAll: {
      name: "isApprovedForAll",
      inputs: [
        { internalType: "address", name: "account", type: "address" },
        { internalType: "address", name: "operator", type: "address" },
      ],
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
      signature: "0xe985e9c5",
    },
    map_NFTData: {
      name: "map_NFTData",
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      outputs: [
        { internalType: "address", name: "nftHolder", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
        { internalType: "bool", name: "nft", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
      signature: "0x0619ec2e",
    },
    map_royaltyInfo: {
      name: "map_royaltyInfo",
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      outputs: [
        { internalType: "uint16", name: "royalty_percentage", type: "uint16" },
        { internalType: "bool", name: "royalty_set", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
      signature: "0xf2b0f5fa",
    },
    royaltyInfo: {
      name: "royaltyInfo",
      inputs: [
        { internalType: "uint256", name: "tokenId", type: "uint256" },
        { internalType: "uint256", name: "value", type: "uint256" },
      ],
      outputs: [
        { internalType: "address", name: "receiver", type: "address" },
        { internalType: "uint256", name: "royaltyAmount", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
      signature: "0x2a55205a",
    },
    safeBatchTransferFrom: {
      name: "safeBatchTransferFrom",
      inputs: [
        { internalType: "address", name: "from", type: "address" },
        { internalType: "address", name: "to", type: "address" },
        { internalType: "uint256[]", name: "ids", type: "uint256[]" },
        { internalType: "uint256[]", name: "amounts", type: "uint256[]" },
        { internalType: "bytes", name: "data", type: "bytes" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0x2eb2c2d6",
    },
    safeTransferFrom: {
      name: "safeTransferFrom",
      inputs: [
        { internalType: "address", name: "from", type: "address" },
        { internalType: "address", name: "to", type: "address" },
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "uint256", name: "amount", type: "uint256" },
        { internalType: "bytes", name: "data", type: "bytes" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0xf242432a",
    },
    tokenPrice: {
      name: "tokenPrice",
      inputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "address", name: "", type: "address" },
      ],
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
      signature: "0xb62d370b",
    },
    uri: {
      name: "uri",
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
      signature: "0x0e89341c",
    },
    supportsInterface: {
      name: "supportsInterface",
      inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
      signature: "0x01ffc9a7",
    },
    mintMASNFT: {
      name: "mintMASNFT",
      inputs: [
        { internalType: "string", name: "_metadataURI", type: "string" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0xed2eebbe",
    },
    mintMASFT: {
      name: "mintMASFT",
      inputs: [
        { internalType: "uint256", name: "_tokenID", type: "uint256" },
        { internalType: "uint256", name: "_amount", type: "uint256" },
        { internalType: "string", name: "_metadataURI", type: "string" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0xe20bebbc",
    },
    setRoyalties: {
      name: "setRoyalties",
      inputs: [
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint16", name: "_royalties", type: "uint16" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0x347bd5fe",
    },
    setApprovalForAll: {
      name: "setApprovalForAll",
      inputs: [],
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0xcc9562a5",
    },
    setForSale: {
      name: "setForSale",
      inputs: [
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_price", type: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0x17fcfe22",
    },
    removeSales: {
      name: "removeSales",
      inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0x1402e219",
    },
    removeSalesAll: {
      name: "removeSalesAll",
      inputs: [
        { internalType: "uint256[]", name: "_tokenIds", type: "uint256[]" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0x6909f134",
    },
    purchaseToken_batch: {
      name: "purchaseToken_batch",
      inputs: [
        { internalType: "uint256[]", name: "_tokenIds", type: "uint256[]" },
        { internalType: "uint256[]", name: "_amounts", type: "uint256[]" },
        { internalType: "address", name: "_sellerAddress", type: "address" },
      ],
      outputs: [],
      stateMutability: "payable",
      type: "function",
      signature: "0x369d6806",
    },
    purchaseToken: {
      name: "purchaseToken",
      inputs: [
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_amount", type: "uint256" },
        { internalType: "address", name: "_sellerAddress", type: "address" },
      ],
      outputs: [],
      stateMutability: "payable",
      type: "function",
      signature: "0x6ffe5e55",
    },
    burn: {
      name: "burn",
      inputs: [
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_burnAmount", type: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
      signature: "0xb390c0ab",
    },
  },
  address: "0x260fdDFCfdfBa40CC01Dc74a16F7E8e13cb08e34",
} as const;
